#!/bin/bash
mkdir build doc
touch README.md
cp /home/jing/usr/shell/maint main.cpp
cp /home/jing/usr/shell/mcmaket CMakeLists.txt 
cp /home/jing/usr/shell/C__gitignore .gitignore
cd doc
cp /home/jing/usr/shell/doc_cmake CMakeLists.txt
cp /home/jing/usr/shell/Doxyfile Doxyfile 
